{
    'name': "shop_customer_auth",
    'summary': "Autenticación, operaciones comerciales y cobros de tienda",
    'description': """
Autenticación de clientes, operaciones de tienda, POS y cobros web.
    """,
    'author': "My Company",
    'website': "https://www.yourcompany.com",
    'category': 'Uncategorized',
    'version': '19.0.1.1.0',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'contacts',
        'sale_management',
        'purchase',
        'stock',
        'account',
        'hr_expense',
        'point_of_sale',
        'website_sale',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'shop_customer_auth/static/src/pos/product_screen.js',
            'shop_customer_auth/static/src/pos/product_screen.xml',
            'shop_customer_auth/static/src/pos/combo_configurator.xml',
            'shop_customer_auth/static/src/pos/pos_product_list.scss',
            'shop_customer_auth/static/src/pos/customer_account.js',
            'shop_customer_auth/static/src/pos/customer_account.xml',
            'shop_customer_auth/static/src/pos/customer_account.scss',
        ],
        'web.assets_backend': [
            'shop_customer_auth/static/src/dashboard/executive_dashboard.js',
            'shop_customer_auth/static/src/dashboard/executive_dashboard.xml',
            'shop_customer_auth/static/src/dashboard/executive_dashboard.scss',
            'shop_customer_auth/static/src/stock/quick_stock_adjustment.js',
            'shop_customer_auth/static/src/stock/quick_stock_adjustment.xml',
            'shop_customer_auth/static/src/stock/quick_stock_adjustment.scss',
        ],
    },
    'data': [
        'security/password_reset_security.xml',
        'security/ir.model.access.csv',
        'data/password_reset_cron.xml',
        'data/product_defaults.xml',
        'views/customer_account_views.xml',
        'views/register_customer_payment_views.xml',
        'views/res_partner_customer_account_views.xml',
        'views/web_customer_views.xml',
        'views/pos_payment_method_customer_account_views.xml',
        'views/customer_account_menu.xml',
        'views/executive_dashboard_views.xml',
        'views/quick_stock_adjustment_views.xml',
        'views/product_template_views.xml',
        'views/product_category_views.xml',
        'views/views.xml',
        'views/templates.xml',
        'views/sale_order_payment_views.xml',
        'views/website_sale_portal_templates.xml',
    ],
    'demo': ['demo/demo.xml'],
}
